Module: Owner.SecureFileUploadGateway

Version: 1.36

Items:
  - Resource: SecureFileUploadGatewayBucket
    Scope: "*"
    Description: Default bucket of file uploads from api gateway
    Type: AWS::S3::Bucket
    Allow: ReadWrite

  - Resource: CustomerUsagePlan
    Description: Limit usage for REST API
    Type: AWS::ApiGateway::UsagePlan
    Properties:
      UsagePlanName: CustomerUsagePlan
      ApiStages:
        - ApiId: !Ref Module::RestApi
          Stage: !Ref Module::RestApi::Stage
      Quota:
        Limit: 100000
        Period: MONTH

    # https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-apikey.html
  - Resource: Customer01ApiKey
    Description: Limit access for customer01
    Type: AWS::ApiGateway::ApiKey
    Properties:
      Description: ApiKey for file uploader
      Enabled: true

  #  - Resource: AddApiKey
  #    Description: Add to usage plan
  #    Type: AWS::ApiGateway::UsagePlanKey
  #    Properties:
  #        KeyId: !Ref Module::RestApi
  #        KeyType: API_KEY
  #        UsagePlanId: !Ref CustomerUsagePlan # 0.5 fixes this

  - Function: GatewayToS3Function
    Description: Post a file to S3 from an Api Gateway request
    Memory: 256
    Timeout: 60
    Sources:
      - Api: POST:/FileUpload
        ApiKeyRequired: true
        OperationName: Endpoint for file uploads
